spring.application.name=literaturas


# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gutendex_db
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Server
server.port=8080

# Gutendex API
gutendex.api.url=https://gutendex.com/books

# Logging
logging.level.com.gutendex=DEBUG
logging.level.org.springframework.web.client=DEBUG